# Archivo de configuración de tmux
# Este archivo será copiado por Ansible a /home/rpi-manolox/.tmux.conf

# Cambia el prefijo de Ctrl+b a Ctrl+a — más cómodo para los dedos
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Numera las ventanas desde 1 en lugar de 0
set -g base-index 1

# Activa el modo ratón — permite hacer clic en ventanas y paneles
set -g mouse on

# Muestra el nombre del host en la barra inferior
set -g status-right "#H"
